const cultureMapping = {
    'Akan': ['Akan', 'Guan', 'Kru'],
    'Arabic': [
        'Bedouin',
        'Egyptian',
        'Maghrebi',
        'Mashriqi',
        'Yemeni'],
    'Baltic': [
        'Latgalian',
        'Lithuanian',
        'Prussian',
    ],
    'Balto-Finnic': [
        'Estonian',
        'Finnish',
        'Karelian',
        'Sami',
        'Vepsian',
    ],
    'Berber': [
        'Baranis',
        'Butr',
        'Zaghawa',
    ],
    'Brythonic': [
        'Breton',
        'Cornish',
        'Cumbrian',
        'Pictish',
        'Welsh',
    ],
    'Burman': [
        'Burmese',
        'Mon',
    ],
    'Byzantine': [
        'Alan',
        'Armenian',
        'Georgian',
        'Greek',
        'Syriac',
    ],
    'Central African': [
        'Hausa',
        'Kanuri',
        'Nupe',
        'Sao',
    ],
    'Central Germanic': [
        'Bavarian',
        'Dutch',
        'Franconian',
        'Frisian',
        'German',
        'Langobard',
        'Saxon',
        'Swabian',
    ],
    'Chinese': ['Han'],
    'Dravidian': [
        'Gond',
        'Kannada',
        'Tamil',
        'Telugu',
    ],
    'East African': [
        'Daju',
        'Ethiopian',
        'Nubian',
        'Welayta',
    ],
    'East Slavic': [
        'Ilmenian',
        'Russian',
        'Severian',
        'Volhynian',
    ],
    'Frankish': [
        'Frankish',
        'French',
        'Norman',
        'Occitan',
    ],
    'Goidelic': [
        'Gaelic',
        'Irish',
    ],
    'Guinean Uplander': [
        'Bobo',
        'Gur',
        'Malinke',
        'Marka',
        'Mel',
    ],
    'Horn African': [
        'Afar',
        'Beja',
        'Somali',
    ],
    'Iberian': [
        'Andalusian',
        'Aragonese',
        'Asturleonese',
        'Basque',
        'Castilian',
        'Catalan',
        'Galician',
        'Portuguese',
        'Suebi',
        'Visigothic',
    ],
    'Indo-Aryan': [
        'Bengali',
        'Gujarati',
        'Kamrupi',
        'Kannauji',
        'Kashmiri',
        'Malvi',
        'Marathi',
        'Nepali',
        'Oriya',
        'Punjabi',
        'Rajasthani',
        'Sindhi',
        'Sinhala',
    ],
    'Iranian': [
        'Afghan',
        'Baloch',
        'Daylamite',
        'Khwarezmian',
        'Kurdish',
        'Persian',
        'Saka',
        'Sogdian',
        'Tajik',
    ],
    'Israelite': [
        'Ashkenazi',
        'Kochinim',
        'Radhanite',
        'Sephardi',
    ],
    'Latin': [
        'Cisalpine',
        'Italian',
        'Lombard',
        'Roman',
        'Sardinian',
        'Sicilian',
    ],
    'Magyar': [
        'Hungarian',
        'Mogyër',
    ],
    'Mongolic': [
        'Buryat',
        'Jurchen',
        'Kerait',
        'Khitan',
        'Mongol',
        'Naiman',
        'Oirat',
        'Öngüd',
        'Tuyuhun',
    ],
    'Niger Delta': [
        'Edo',
        'Ewe',
        'Igbo',
        'Yoruba',
    ],
    'North Germanic': [
        'Danish',
        'Norse',
        'Norwegian',
        'Swedish',
    ],
    'Qiangic': [
        'Qiang',
        'Tangut',
    ],
    'Sahelian': [
        'Bozo',
        'Gaw',
        'Mossi',
        'Songhai',
        'Soninke',
        'Sorko',
    ],
    'Senegambian': [
        'Pulaar',
        'Serer',
        'Wolof',
    ],
    'South Slavic': [
        'Bosnian',
        'Bulgarian',
        'Croatian',
        'Serbian',
    ],
    'Tibetan': [
        'Bodpa',
        'Kirati',
        'Lhomon',
        'Sumpa',
        'Tsangpa',
        'Zhangzhung',
    ],
    'Tocharian': ['Tocharian'],
    'Turkic': [
        'Avar',
        'Bashkir',
        'Bolghar',
        'Chuvash',
        'Cuman',
        'Karluk',
        'Khazar',
        'Kimek',
        'Kipchak',
        'Kirghiz',
        'Laktan',
        'Oghuz',
        'Pecheneg',
        'Shatuo',
        'Uriankhai',
        'Uyghur',
        'Yughur',
    ],
    'Ugro-Permian': [
        'Bjarmian',
        'Ostyak',
        'Permian',
    ],
    'Vlach': ['Vlach'],
    'Volga-Finnic': [
        'Mari',
        'Merya',
        'Meshchera',
        'Mordvin',
        'Muroma',
    ],
    'West Germanic': [
        'Anglo-Saxon',
        'English',
        'Old Saxon',
        'Scots',
    ],
    'West Slavic': [
        'Carantanian',
        'Czech',
        'Polabian',
        'Polish',
        'Pomeranian',
        'Slovien',
    ],
}

export default cultureMapping;